[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[context.production.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.60.1"

[context.branch-deploy]
command = "hugo -b $URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.60.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
